flowCrm:
  baseurl: http://localhost:8080
  security:
    jwt:
      jwtPrivateFile: classpath:jwt-keys/private.pem
      jwtPublicFile: classpath:jwt-keys/public-key.pem
      tokenExpirationTime: 86400
      tokenIssuer: flowCrm
  token:
    header:
      name: Authorization
debug: false
logging:
  file:
    name: ./logs/FlowCrmRest.log
  level:
    org:
      apache: ERROR
      hibernate:
        SQL: OFF
      spring: ERROR
    root: ERROR
    com:
      dogan:
        bilisim: INFO
server:
  port: 8080
json:
  log:
    pretty: true
spring:
  debug: false
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 10000
      maxLifetime: 2000000
      maximumPoolSize: 5
      minimumIdle: 1
      poolName: SpringBootJPAHikariCP
    password: oQNB9qfiXoGZCoimdqPf
    url: jdbc:sqlserver://localhost:1433;databaseName=flow-crm;encrypt=true;trustServerCertificate=true
    username: sa
  jackson:
    default-property-inclusion: NON_NULL
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      show_sql: false
      ddl-auto: update
      hbm2ddl:
        auto: update
      jdbc:
        time_zone: UTC
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        default_catalog: flow-crm
        default_schema: dbo
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        show_sql: false
        use_sql_comments: false
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

# https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors?view=sql-server-ver15
database.vendor.error:
  codes:
    2627:
      message: "Validation.constraint.violation.duplicate.key"
      errorCode: UNIQUE_CONSTRAINS

database:
  init:
    system-owner:
      insert: true
      username: systemOwner
      password: 12345678a


